# Project: GTI Tugas 1
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Tugas1/main.o
LINKOBJ  = Tugas1/main.o
LIBS     = -L"C:/Users/Lenovo PC/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/lib" -L"C:/Users/Lenovo PC/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -mwindows -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32
INCS     = -I"C:/Users/Lenovo PC/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/include" -I"C:/Users/Lenovo PC/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/Lenovo PC/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/Lenovo PC/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/include" -I"C:/Users/Lenovo PC/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/Lenovo PC/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Users/Lenovo PC/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = "Tugas1 Bumi Bulan.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) -DGLUT_STATIC
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Tugas1/main.o: Tugas1/main.cpp
	$(CPP) -c Tugas1/main.cpp -o Tugas1/main.o $(CXXFLAGS)
